
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josh
 */
public class BotonesSeleccionFinal extends javax.swing.JFrame {

    /**
     * Creates new form BotonesSeleccionFinal
     */
    public BotonesSeleccionFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtSignosZodiacales = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DerEscorpio = new javax.swing.JRadioButton();
        DerSagitario = new javax.swing.JRadioButton();
        DerCapricornio = new javax.swing.JRadioButton();
        DerAcuario = new javax.swing.JRadioButton();
        DerTauro = new javax.swing.JRadioButton();
        DerAries = new javax.swing.JRadioButton();
        DerGeminis = new javax.swing.JRadioButton();
        DerCancer = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        DerLeo = new javax.swing.JRadioButton();
        DerVirgo = new javax.swing.JRadioButton();
        DerLibra = new javax.swing.JRadioButton();
        DerPiscis = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        BtSignosZodiacales.add(DerEscorpio);
        DerEscorpio.setText("Escorpio");

        BtSignosZodiacales.add(DerSagitario);
        DerSagitario.setText("Sagitario");
        DerSagitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerSagitarioActionPerformed(evt);
            }
        });

        BtSignosZodiacales.add(DerCapricornio);
        DerCapricornio.setText("Capricornio ");

        BtSignosZodiacales.add(DerAcuario);
        DerAcuario.setText("Acuario");

        BtSignosZodiacales.add(DerTauro);
        DerTauro.setText("Tauro");

        BtSignosZodiacales.add(DerAries);
        DerAries.setText("Aries");

        BtSignosZodiacales.add(DerGeminis);
        DerGeminis.setText("Geminis");

        BtSignosZodiacales.add(DerCancer);
        DerCancer.setText("Cancer");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccion de signo zodiacal");

        BtSignosZodiacales.add(DerLeo);
        DerLeo.setText("Leo");

        BtSignosZodiacales.add(DerVirgo);
        DerVirgo.setText("Virgo");

        BtSignosZodiacales.add(DerLibra);
        DerLibra.setText("Libra");

        BtSignosZodiacales.add(DerPiscis);
        DerPiscis.setText("Piscis");

        jButton1.setText("Seleccionar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DerLeo)
                            .addComponent(DerVirgo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(DerCancer)
                            .addComponent(DerAcuario)
                            .addComponent(DerCapricornio)
                            .addComponent(DerSagitario)
                            .addComponent(DerTauro)
                            .addComponent(DerAries)
                            .addComponent(DerGeminis)
                            .addComponent(DerLibra)
                            .addComponent(DerEscorpio))
                        .addContainerGap(136, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DerPiscis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalir)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(DerAries)
                .addGap(18, 18, 18)
                .addComponent(DerTauro)
                .addGap(18, 18, 18)
                .addComponent(DerGeminis)
                .addGap(18, 18, 18)
                .addComponent(DerCancer)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(DerLeo)
                        .addGap(18, 18, 18)
                        .addComponent(DerVirgo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(DerLibra)
                .addGap(18, 18, 18)
                .addComponent(DerEscorpio)
                .addGap(18, 18, 18)
                .addComponent(DerSagitario)
                .addGap(18, 18, 18)
                .addComponent(DerCapricornio)
                .addGap(18, 18, 18)
                .addComponent(DerAcuario)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DerPiscis)
                    .addComponent(BtnSalir))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DerSagitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerSagitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DerSagitarioActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        if (DerAries.isSelected()){
            JOptionPane.showMessageDialog(null,"Su signo zodiacal es Aries");
        }else if (DerTauro.isSelected()){
            JOptionPane.showMessageDialog(null,"Su signo zodiacal es Tauro");
        }else if (DerGeminis.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Geminis");
        }else if (DerCancer.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Cancer");
        }else if (DerLeo.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Leo");
        }else if (DerVirgo.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodialcal es Virgo");
        }else if (DerLibra.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Libra");
        }else if (DerEscorpio.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Escorpio");
        }else if (DerSagitario.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Sagitario");
        }else if (DerCapricornio.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Capricornio");
        }else if (DerAcuario.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Acuario");
        }else if (DerPiscis.isSelected()){
            JOptionPane.showMessageDialog(null, "Su signo zodiacal es Piscis");
        }
        
        
            
    }//GEN-LAST:event_jButton1MouseClicked

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_BtnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonesSeleccionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonesSeleccionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonesSeleccionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonesSeleccionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonesSeleccionFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtSignosZodiacales;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JRadioButton DerAcuario;
    private javax.swing.JRadioButton DerAries;
    private javax.swing.JRadioButton DerCancer;
    private javax.swing.JRadioButton DerCapricornio;
    private javax.swing.JRadioButton DerEscorpio;
    private javax.swing.JRadioButton DerGeminis;
    private javax.swing.JRadioButton DerLeo;
    private javax.swing.JRadioButton DerLibra;
    private javax.swing.JRadioButton DerPiscis;
    private javax.swing.JRadioButton DerSagitario;
    private javax.swing.JRadioButton DerTauro;
    private javax.swing.JRadioButton DerVirgo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
