/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author josh
 */
public class Textos extends javax.swing.JFrame {

    /**
     * Creates new form Textos
     */
    public Textos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbAire = new javax.swing.JLabel();
        LbAgua = new javax.swing.JLabel();
        LbSuelo = new javax.swing.JLabel();
        LbSustancias = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        LbAire.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LbAire.setForeground(new java.awt.Color(255, 255, 255));
        LbAire.setText("Contaminacion del aire");
        LbAire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbAireMouseClicked(evt);
            }
        });

        LbAgua.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LbAgua.setForeground(new java.awt.Color(255, 255, 255));
        LbAgua.setText("Contaminacion del agua");
        LbAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbAguaMouseClicked(evt);
            }
        });

        LbSuelo.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LbSuelo.setForeground(new java.awt.Color(255, 255, 255));
        LbSuelo.setText("Contaminacion del suelo");
        LbSuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSueloMouseClicked(evt);
            }
        });

        LbSustancias.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LbSustancias.setForeground(new java.awt.Color(255, 255, 255));
        LbSustancias.setText("Sustancias contaminantes");
        LbSustancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSustanciasMouseClicked(evt);
            }
        });

        BtnRegresar.setText("Regresar");
        BtnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbAgua)
                    .addComponent(LbAire, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbSuelo)
                    .addComponent(LbSustancias))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegresar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAire)
                    .addComponent(LbSuelo))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAgua)
                    .addComponent(LbSustancias))
                .addGap(60, 60, 60)
                .addComponent(BtnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseClicked
        
        Inicio I = new Inicio();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnRegresarMouseClicked

    private void LbAireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAireMouseClicked
       
        Aire A = new Aire();
        A.setVisible(true);
        dispose();
    }//GEN-LAST:event_LbAireMouseClicked

    private void LbAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAguaMouseClicked
       
        Agua G = new Agua();
        G.setVisible(true);
        dispose();
    }//GEN-LAST:event_LbAguaMouseClicked

    private void LbSueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSueloMouseClicked
       
        Suelo S = new Suelo();
        S.setVisible(true);
        dispose();
                
    }//GEN-LAST:event_LbSueloMouseClicked

    private void LbSustanciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSustanciasMouseClicked
        
        Sustancias U = new Sustancias();
        U.setVisible(true);
        dispose();
    }//GEN-LAST:event_LbSustanciasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Textos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Textos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Textos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Textos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Textos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel LbAgua;
    private javax.swing.JLabel LbAire;
    private javax.swing.JLabel LbSuelo;
    private javax.swing.JLabel LbSustancias;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
