/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.math.*;
/**
 *
 * @author josh
 */
public class OperacionesVisual extends javax.swing.JFrame {

    /**
     * Creates new form OperacionesVisual
     */
    public OperacionesVisual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CajaNum1 = new javax.swing.JTextField();
        CajaNum2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CajaRaiz = new javax.swing.JTextField();
        CajaExponente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BotonRaiz = new javax.swing.JButton();
        BotonExponente = new javax.swing.JButton();
        BotonSumaDesimal = new javax.swing.JButton();
        BotonRestarDesimales = new javax.swing.JButton();
        BotonMultiplicarDesimales = new javax.swing.JButton();
        BotonDividirDesimales = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BotonSumaEnteros = new javax.swing.JButton();
        BotonRestaEnteros = new javax.swing.JButton();
        BotonMultiplicarEnteros = new javax.swing.JButton();
        BotonDividirEnteros = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CajaResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa el primer numero: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresa el segundo numero: ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desimales");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Raiz:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("De:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Exponente");

        BotonRaiz.setText("Raiz");
        BotonRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRaizMouseClicked(evt);
            }
        });

        BotonExponente.setText("Exponente");
        BotonExponente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonExponenteMouseClicked(evt);
            }
        });

        BotonSumaDesimal.setText("Sumar");
        BotonSumaDesimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSumaDesimalMouseClicked(evt);
            }
        });

        BotonRestarDesimales.setText("Restar");
        BotonRestarDesimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRestarDesimalesMouseClicked(evt);
            }
        });

        BotonMultiplicarDesimales.setText("Multiplicar");
        BotonMultiplicarDesimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMultiplicarDesimalesMouseClicked(evt);
            }
        });

        BotonDividirDesimales.setText("Dividir");
        BotonDividirDesimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDividirDesimalesMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enteros");

        BotonSumaEnteros.setText("Sumar Enteros");
        BotonSumaEnteros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSumaEnterosMouseClicked(evt);
            }
        });

        BotonRestaEnteros.setText("Restar Enteros");
        BotonRestaEnteros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRestaEnterosMouseClicked(evt);
            }
        });

        BotonMultiplicarEnteros.setText("Multiplicar Enteros");
        BotonMultiplicarEnteros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMultiplicarEnterosMouseClicked(evt);
            }
        });

        BotonDividirEnteros.setText("Dividir Enteros");
        BotonDividirEnteros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDividirEnterosMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resultado");

        CajaResultado.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CajaNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CajaNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonSumaDesimal)
                                    .addComponent(BotonMultiplicarDesimales))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonDividirDesimales)
                                    .addComponent(BotonRestarDesimales))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CajaRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(CajaExponente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel7)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addComponent(BotonExponente)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonRaiz)
                                .addGap(123, 123, 123)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonSumaEnteros)
                        .addGap(60, 60, 60)
                        .addComponent(BotonRestaEnteros)
                        .addGap(54, 54, 54)
                        .addComponent(BotonMultiplicarEnteros)
                        .addGap(47, 47, 47)
                        .addComponent(BotonDividirEnteros)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(29, 29, 29)
                        .addComponent(CajaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(279, 279, 279))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CajaNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(CajaRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CajaExponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CajaNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonRaiz)
                            .addComponent(BotonExponente)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonSumaDesimal)
                            .addComponent(BotonRestarDesimales))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMultiplicarDesimales)
                    .addComponent(BotonDividirDesimales))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CajaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSumaEnteros)
                    .addComponent(BotonRestaEnteros)
                    .addComponent(BotonMultiplicarEnteros)
                    .addComponent(BotonDividirEnteros))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSumaDesimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSumaDesimalMouseClicked
       double Num1 = Double.parseDouble(CajaNum1.getText());
       double Num2 = Double.parseDouble(CajaNum2.getText());
       
       CajaResultado.setText(String.valueOf(Num1 + Num2));
       
       
    }//GEN-LAST:event_BotonSumaDesimalMouseClicked

    private void BotonRestarDesimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRestarDesimalesMouseClicked
       
        double Num1 = Double.parseDouble(CajaNum1.getText());
        double Num2 = Double.parseDouble(CajaNum2.getText());
        
        CajaResultado.setText(String.valueOf(Num1 - Num2));
        
        
    }//GEN-LAST:event_BotonRestarDesimalesMouseClicked

    private void BotonMultiplicarDesimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMultiplicarDesimalesMouseClicked
       
        double Num1 = Double.parseDouble(CajaNum1.getText());
        double Num2 = Double.parseDouble(CajaNum2.getText());
        
        CajaResultado.setText(String.valueOf(Num1 * Num2));
        
        
    }//GEN-LAST:event_BotonMultiplicarDesimalesMouseClicked

    private void BotonDividirDesimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDividirDesimalesMouseClicked
        
        double Num1 = Double.parseDouble(CajaNum1.getText());
        double Num2 = Double.parseDouble(CajaNum2.getText());
        
        CajaResultado.setText(String.valueOf(Num1/Num2));
        
    }//GEN-LAST:event_BotonDividirDesimalesMouseClicked

    private void BotonRaizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRaizMouseClicked
        
        double Raiz = Double.parseDouble(CajaRaiz.getText());
        double Exponente = Double.parseDouble(CajaExponente.getText());
        
        double Resultado = Math.pow(Exponente, 1/Raiz);
        
        CajaResultado.setText(String.valueOf(Resultado));
        
        
        
    }//GEN-LAST:event_BotonRaizMouseClicked

    private void BotonExponenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExponenteMouseClicked
       
        double Numero = Double.parseDouble(CajaRaiz.getText());
        double Exponente = Double.parseDouble(CajaExponente.getText());
        
        CajaResultado.setText(String.valueOf(Math.pow(Numero, Exponente)));
        
    }//GEN-LAST:event_BotonExponenteMouseClicked

    private void BotonSumaEnterosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSumaEnterosMouseClicked
       
        int Num1 = Integer.parseInt(CajaNum1.getText());
        int Num2 = Integer.parseInt(CajaNum2.getText());
        
        CajaResultado.setText(String.valueOf(Num1 + Num2));
        
    }//GEN-LAST:event_BotonSumaEnterosMouseClicked

    private void BotonRestaEnterosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRestaEnterosMouseClicked
        
        int Num1 = Integer.parseInt(CajaNum1.getText());
        int Num2 = Integer.parseInt(CajaNum2.getText());
        
        CajaResultado.setText(String.valueOf(Num1 - Num2));
        
        
    }//GEN-LAST:event_BotonRestaEnterosMouseClicked

    private void BotonMultiplicarEnterosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMultiplicarEnterosMouseClicked
        
        int Num1 = Integer.parseInt(CajaNum1.getText());
        int Num2 = Integer.parseInt(CajaNum2.getText());
        
        CajaResultado.setText(String.valueOf(Num1 * Num2));
        
    }//GEN-LAST:event_BotonMultiplicarEnterosMouseClicked

    private void BotonDividirEnterosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDividirEnterosMouseClicked
        
        int Num1 = Integer.parseInt(CajaNum1.getText());
        int Num2 = Integer.parseInt(CajaNum2.getText());
        
        CajaResultado.setText(String.valueOf(Num1/Num2));
    }//GEN-LAST:event_BotonDividirEnterosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionesVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDividirDesimales;
    private javax.swing.JButton BotonDividirEnteros;
    private javax.swing.JButton BotonExponente;
    private javax.swing.JButton BotonMultiplicarDesimales;
    private javax.swing.JButton BotonMultiplicarEnteros;
    private javax.swing.JButton BotonRaiz;
    private javax.swing.JButton BotonRestaEnteros;
    private javax.swing.JButton BotonRestarDesimales;
    private javax.swing.JButton BotonSumaDesimal;
    private javax.swing.JButton BotonSumaEnteros;
    private javax.swing.JTextField CajaExponente;
    private javax.swing.JTextField CajaNum1;
    private javax.swing.JTextField CajaNum2;
    private javax.swing.JTextField CajaRaiz;
    private javax.swing.JTextField CajaResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
