
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author josh
 */
public class HoroscoposVisual extends javax.swing.JFrame {

    /**
     * Creates new form HoroscoposVisual
     */
    public HoroscoposVisual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtDia = new javax.swing.JTextField();
        BtnConsultar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        CmbMes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Horoscopo");

        jLabel2.setText("Ingresa el dia de nacimiento");

        jLabel3.setText("Ingresa el mes de nacimiento");

        BtnConsultar.setText("Consultar");
        BtnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConsultarMouseClicked(evt);
            }
        });

        BtnLimpiar.setText("Nueva consulta");
        BtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarMouseClicked(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });

        CmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar-", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtDia)
                            .addComponent(CmbMes, 0, 140, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BtnConsultar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(BtnLimpiar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(BtnConsultar)
                .addGap(54, 54, 54)
                .addComponent(BtnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConsultarMouseClicked

        int dia = Integer.parseInt(TxtDia.getText());
        String mes = (String) CmbMes.getSelectedItem();

        if (dia >= 21 && mes.equals("Marzo") || dia <= 20 && mes.equals("Abril")) {
            JOptionPane.showMessageDialog(null, "Aries\n Es un día místico y mágico, pues tenemos una luna azul hoy");
        } else if (dia >= 21 && mes.equals("Abril") || dia <= 20 && mes.equals("Mayo")) {
            JOptionPane.showMessageDialog(null, "Tauro\n Siendo un día contrastante, no olvides de realizar las cosas importantes en tu itinerario.");
        } else if (dia >= 21 && mes.equals("Mayo") || dia <= 21 && mes.equals("Junio")) {
            JOptionPane.showMessageDialog(null, "Geminis\n Hablando de experiencia, aprendizaje y conocimiento, podrías ser uno de los mejores ejemplos a observar");
        } else if (dia >= 22 && mes.equals("Junio") || dia <= 22 && mes.equals("Julio")) {
            JOptionPane.showMessageDialog(null, "Cancer\n El día es próspero en el mejor sentido de la palabra");
        } else if (dia >= 23 && mes.equals("Julio") || dia <= 22 && mes.equals("Agosto")) {
            JOptionPane.showMessageDialog(null, "Leon\n Te llenas de energía con la Luna y estarás en equilibrio");
        } else if (dia >= 23 && mes.equals("Agosto") || dia <= 22 && mes.equals("Septiembre")) {
            JOptionPane.showMessageDialog(null, "Virgo\n Podrás delegar bien todas las ideas que tienes en la cabeza.");
        } else if (dia >= 23 && mes.equals("Septiembre") || dia <= 22 && mes.equals("Octubre")) {
            JOptionPane.showMessageDialog(null, "Libra\n Vienen cambios de mentalidad y energía");
        } else if (dia >= 23 && mes.equals("Octubre") || dia <= 21 && mes.equals("Noviembre")) {
            JOptionPane.showMessageDialog(null, "Escorpio\n Estarías listo para actuar ante las adversidades de Mercurio");
        } else if (dia >= 22 && mes.equals("Noviembre") || dia <= 21 && mes.equals("Diciembre")) {
            JOptionPane.showMessageDialog(null, "Sagitario\n Exponerte a la energía Lunar hoy, implicaría que todo se sienta mucho mejor para ti, pues estarías haciendo que su regencia influya en un evento de Luna Azul tan particular.");
        } else if (dia >= 22 && mes.equals("Diciembre") || dia <= 20 && mes.equals("Enero")) {
            JOptionPane.showMessageDialog(null, "Capricornio\n Luna Azul, luna llena de prosperidad sin duda ahora estarán algunas ideas sueltas que tienes que cachar para poner en orden");
        } else if (dia >= 21 && mes.equals("Enero") || dia <= 19 && mes.equals("Febrero")) {
            JOptionPane.showMessageDialog(null, "Acuario\n En sí es la Luna Azul, inesperada y bella, que con su energía haría que todo estuviera en un camino lleno de flores sin exagerar. ");
        } else if (dia >= 20 && mes.equals("Febrero") || dia <= 20 && mes.equals("Marzo")) {
            JOptionPane.showMessageDialog(null, "Piscis\n Elimina los malos pensamientos, deja que todo surja en buena energía, si alguien estuviera haciendo alguna intervención incorrecta en tu andar, lo notarás y te alejarías para evitar malos entendidos.");
        }

    }//GEN-LAST:event_BtnConsultarMouseClicked

    private void BtnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarMouseClicked

        TxtDia.setText(null);
        CmbMes.setSelectedIndex(0);
    }//GEN-LAST:event_BtnLimpiarMouseClicked

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked

        System.exit(0);

    }//GEN-LAST:event_BtnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoroscoposVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoroscoposVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoroscoposVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoroscoposVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoroscoposVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> CmbMes;
    private javax.swing.JTextField TxtDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
